-- Seed Türk Hava Kurumu, European University of Lefke, and Fatih Sultan Mehmet programs.
-- Source: agentportal screenshots 2026-05-17. Bulk INSERT per university for fast Flyway startup.

INSERT INTO program (id, university_id, name, degree, language, cost, years, created_at, available, name_ar, before_discount, cash_price, updated_at)
SELECT gen_random_uuid(), u.id,
  v.name, v.degree, v.language, v.cost, v.years, now(), v.available, v.name_ar, v.before_discount, v.cash_price, now()
FROM university u
CROSS JOIN (
  VALUES
  ('Agricultural Management', 'Bachelor', 'Turkish', 2300, 4, true, 'الإدارة الزراعية', 2300, NULL::numeric),
  ('Architecture', 'Bachelor', 'Turkish', 2300, 4, true, 'هندسة معمارية', 2300, NULL::numeric),
  ('Banking And Finance', 'Bachelor', 'Turkish', 2300, 4, true, 'بنوك وتمويل', 2300, NULL::numeric),
  ('Business Administration', 'Bachelor', 'Turkish', 2300, 4, true, 'إدارة الأعمال', 2300, NULL::numeric),
  ('Civil Engineering', 'Bachelor', 'Turkish', 2300, 4, true, 'الهندسة المدنية', 2300, NULL::numeric),
  ('Clinical Pharmacy', 'Bachelor', 'Turkish', 3100, 6, true, 'الصيدلة السريرية', 3100, NULL::numeric),
  ('Computer Engineering', 'Bachelor', 'Turkish', 2300, 4, true, 'هندسة كمبيوتر', 2300, NULL::numeric),
  ('Computer Information Systems', 'Bachelor', 'Turkish', 2300, 4, true, 'أنظمة المعلومات الحاسوبية', 2300, NULL::numeric),
  ('Digital Game Design', 'Bachelor', 'Turkish', 2300, 4, true, 'تصميم الألعاب الرقمية', 2300, NULL::numeric),
  ('Economics', 'Bachelor', 'Turkish', 2300, 4, true, 'الاقتصاد', 2300, NULL::numeric),
  ('Electrical And Electronic Engineering', 'Bachelor', 'Turkish', 2300, 4, true, 'هندسة كهرباء والكترون', 2300, NULL::numeric),
  ('Electronics And Communication Engineering', 'Bachelor', 'Turkish', 2300, 4, true, 'هندسة الالكترونيات والاتصالات', 2300, NULL::numeric),
  ('English Language Teaching', 'Bachelor', 'Turkish', 2300, 4, true, 'تدريس اللغة الانجليزية', 2300, NULL::numeric),
  ('Environmental Engineering', 'Bachelor', 'Turkish', 2300, 4, true, 'هندسة بيئية', 2300, NULL::numeric),
  ('Gastronomy And Culinary Arts', 'Bachelor', 'Turkish', 2300, 4, true, 'فنون الطهي والمطبخ', 2300, NULL::numeric),
  ('Human Resources Management', 'Bachelor', 'Turkish', 2300, 4, true, 'إدارة الموارد البشرية', 2300, NULL::numeric),
  ('Industrial Product Design', 'Bachelor', 'Turkish', 2300, 4, true, 'تصميم المنتجات الصناعية', 2300, NULL::numeric),
  ('Information System And Technologies', 'Bachelor', 'Turkish', 2300, 4, true, 'نظم وتقنيات المعلومات', 2300, NULL::numeric),
  ('Interior Architecture And Environmental Design', 'Bachelor', 'Turkish', 2300, 4, true, 'العمارة الداخلية والتصميم البيئي', 2300, NULL::numeric),
  ('International Law', 'Bachelor', 'Turkish', 2300, 4, true, 'القانون الدولي', 2300, NULL::numeric),
  ('International Relations', 'Bachelor', 'Turkish', 2300, 4, true, 'علاقات دولية', 2300, NULL::numeric),
  ('Journalism', 'Bachelor', 'Turkish', 2300, 4, true, 'صحافة', 2300, NULL::numeric),
  ('Logistics Management', 'Bachelor', 'Turkish', 2300, 4, true, 'إدارة اللوجستية', 2300, NULL::numeric),
  ('Management Information Systems', 'Bachelor', 'Turkish', 2300, 4, true, 'نظم المعلومات الادارية', 2300, NULL::numeric),
  ('Marketing', 'Bachelor', 'Turkish', 2300, 4, true, 'تسويق', 2300, NULL::numeric),
  ('Media And Communications', 'Bachelor', 'Turkish', 2300, 4, true, 'الاعلام والاتصالات', 2300, NULL::numeric),
  ('Molecular Biology And Genetics', 'Bachelor', 'Turkish', 2300, 4, true, 'البيولوجيا الجزيئية وعلم الوراثة', 2300, NULL::numeric),
  ('New Media And Communication', 'Bachelor', 'Turkish', 2300, 4, true, 'الإعلام الجديد والاتصالات', 2300, NULL::numeric),
  ('New Media And Journalism', 'Bachelor', 'Turkish', 2300, 4, true, 'الإعلام الجديد والصحافة', 2300, NULL::numeric),
  ('Nursing', 'Bachelor', 'Turkish', 2300, 4, true, 'تمريض', 2300, NULL::numeric),
  ('Nutrition And Dietetics', 'Bachelor', 'Turkish', 2300, 4, true, 'التغذية والحمية', 2300, NULL::numeric),
  ('Pharmacy', 'Bachelor', 'Turkish', 3100, 5, true, 'الصيدلة', 3100, NULL::numeric),
  ('Physiotherapy And Rehabilitation', 'Bachelor', 'Turkish', 2300, 4, true, 'العلاج الطبيعي وإعادة التأهيل', 2300, NULL::numeric),
  ('Political Science And Public Administration', 'Bachelor', 'Turkish', 2300, 4, true, 'العلوم السياسية والإدارة العامة', 2300, NULL::numeric),
  ('Psychology', 'Bachelor', 'Turkish', 2300, 4, true, 'علم النفس', 2300, NULL::numeric),
  ('Public Relations And Advertising', 'Bachelor', 'Turkish', 2300, 4, true, 'العلاقات العامة والدعاية والاعلان', 2300, NULL::numeric),
  ('Software Engineering', 'Bachelor', 'Turkish', 2300, 4, true, 'هندسة البرمجيات', 2300, NULL::numeric),
  ('Tourism Management', 'Bachelor', 'Turkish', 2300, 4, true, 'إدارة السياحة', 2300, NULL::numeric),
  ('Visual Communication Design', 'Bachelor', 'Turkish', 2300, 4, true, 'تصميم الاتصالات البصرية', 2300, NULL::numeric),
  ('horticulture', 'Bachelor', 'Turkish', 2300, 4, true, 'البستنة', 2300, NULL::numeric),
  ('international business commerce', 'Bachelor', 'Turkish', 2300, 4, true, 'التجارة الدولية', 2300, NULL::numeric),
  ('international logistics transportation', 'Bachelor', 'Turkish', 2300, 4, true, 'النقل اللوجستي الدولي', 2300, NULL::numeric),
  ('Agricultural Machinery', 'Diploma', 'Turkish', 2300, 2, true, 'الآلات الزراعية', 2300, NULL::numeric),
  ('Agricultural Technology', 'Diploma', 'Turkish', 2300, 2, true, 'التكنولوجيا الزراعية', 2300, NULL::numeric),
  ('Alternative Energy And Sources Technology', 'Diploma', 'Turkish', 2300, 2, true, 'تكنولوجيا الطاقة البديلة والمصادر', 2300, NULL::numeric),
  ('Architectural Restoration', 'Diploma', 'Turkish', 2300, 2, true, 'الترميم المعماري', 2300, NULL::numeric),
  ('Banking And Insurance', 'Diploma', 'Turkish', 2300, 2, true, 'الخدمات المصرفية والتأمين', 2300, NULL::numeric),
  ('Business Administration', 'Diploma', 'Turkish', 2300, 2, true, 'إدارة الأعمال', 2300, NULL::numeric),
  ('Computer Aided Design And Animation', 'Diploma', 'Turkish', 2300, 2, true, 'التصميم بمساعدة الكمبيوتر والرسوم المتحركة', 2300, NULL::numeric),
  ('Computer Programming', 'Diploma', 'Turkish', 2300, 2, true, 'برمجة الكمبيوتر', 2300, NULL::numeric),
  ('Construction Technology', 'Diploma', 'Turkish', 2300, 2, true, 'تكنولوجيا البناء', 2300, NULL::numeric),
  ('Digital Media And Marketing', 'Diploma', 'Turkish', 2300, 2, true, 'الوسائط الرقمية والتسويق', 2300, NULL::numeric),
  ('Environmental Protection And Control', 'Diploma', 'Turkish', 2300, 2, true, 'حماية البيئة والتحكم فيها', 2300, NULL::numeric),
  ('Information Security Technologies', 'Diploma', 'Turkish', 2300, 2, true, 'تقنيات أمن المعلومات', 2300, NULL::numeric),
  ('Interior Design', 'Diploma', 'Turkish', 2300, 2, true, 'تصميم داخلي', 2300, NULL::numeric),
  ('Oral And Dental Health', 'Diploma', 'Turkish', 2300, 2, true, 'صحة الفم والأسنان', 2300, NULL::numeric),
  ('Public Relations And Advertising', 'Diploma', 'Turkish', 2300, 2, true, 'العلاقات العامة والدعاية والاعلان', 2300, NULL::numeric),
  ('Tourism And Hotel Management', 'Diploma', 'Turkish', 2300, 2, true, 'إدارة السياحة والفنادق', 2300, NULL::numeric),
  ('Agricultural Management With Thesis', 'Master', 'English', 2400, 2, true, 'الإدارة الزراعية مع أطروحة', 4000, NULL::numeric),
  ('Banking And Finance With Thesis', 'Master', 'Turkish', 2400, 2, true, 'بنوك وتمويل مع أطروحة', 4000, NULL::numeric),
  ('Business Administration With Thesis', 'Master', 'Turkish', 2400, 2, true, 'إدارة الأعمال مع أطروحة', 4000, NULL::numeric),
  ('Civil Engineering With Thesis', 'Master', 'Turkish', 2400, 2, true, 'الهندسة المدنية مع أطروحة', 4000, NULL::numeric),
  ('Computer Information Systems With Thesis', 'Master', 'Turkish', 2400, 2, true, 'أنظمة المعلومات الحاسوبية مع أطروحة', 4000, NULL::numeric),
  ('Data Science With Thesis', 'Master', 'Turkish', 2400, 2, true, 'علوم البيانات مع أطروحة', 4000, NULL::numeric),
  ('Digital Media Marketing With Thesis', 'Master', 'Turkish', 2400, 2, true, 'التسويق عبر الوسائط الرقمية مع أطروحة', 4000, NULL::numeric),
  ('Economics With Thesis', 'Master', 'Turkish', 2400, 2, true, 'الاقتصاد مع أطروحة', 4000, NULL::numeric),
  ('Electrical And Electronic Engineering', 'Master', 'Turkish', 2400, 1, true, 'الهندسة الكهربائية والإلكترونية', 4000, NULL::numeric),
  ('English Language Teaching With Thesis', 'Master', 'Turkish', 2400, 2, true, 'تدريس اللغة الانجليزية مع أطروحة', 4000, NULL::numeric),
  ('Environmental Sciences With Thesis', 'Master', 'Turkish', 2400, 2, true, 'العلوم البيئية مع أطروحة', 4000, NULL::numeric),
  ('Health Management With Thesis', 'Master', 'Turkish', 2400, 2, true, 'الإدارة الصحية مع أطروحة', 4000, NULL::numeric),
  ('Horticultural Production With Thesis', 'Master', 'Turkish', 2400, 2, true, 'الإنتاج البستاني مع أطروحة', 4000, NULL::numeric),
  ('Interior Architecture With Thesis', 'Master', 'Turkish', 2400, 2, true, 'عمارة داخلية مع أطروحة', 4000, NULL::numeric),
  ('International Economics And Finance With Thesis', 'Master', 'Turkish', 2400, 2, true, 'الاقتصاد الدولي والمالية مع أطروحة', 4000, NULL::numeric),
  ('International Law With Thesis', 'Master', 'Turkish', 2400, 2, true, 'القانون الدولي مع أطروحة', 4000, NULL::numeric),
  ('International Relations With Thesis', 'Master', 'Turkish', 2400, 2, true, 'علاقات دولية مع أطروحة', 4000, NULL::numeric),
  ('Management Information Systems With Thesis', 'Master', 'Turkish', 2400, 2, true, 'نظم المعلومات الادارية مع أطروحة', 4000, NULL::numeric),
  ('Marketing Management With Thesis', 'Master', 'Turkish', 2400, 2, true, 'إدارة التسويق مع أطروحة', 4000, NULL::numeric),
  ('Nursing With Thesis', 'Master', 'Turkish', 2400, 2, true, 'تمريض مع أطروحة', 4000, NULL::numeric),
  ('Nutrition And Dietetics With Thesis', 'Master', 'Turkish', 2400, 2, true, 'التغذية وعلم التغذية مع أطروحة', 4000, NULL::numeric),
  ('Physiotherapy And Rehabilitation With Thesis', 'Master', 'Turkish', 2400, 2, true, 'العلاج الطبيعي وإعادة التأهيل مع أطروحة', 4000, NULL::numeric),
  ('Plant Sciences And Technologies With Thesis', 'Master', 'Turkish', 2400, 2, true, 'علوم النبات والتقنيات مع أطروحة', 4000, NULL::numeric),
  ('Psychology With Thesis', 'Master', 'Turkish', 2400, 2, true, 'علم نفس مع أطروحة', 4000, NULL::numeric),
  ('Public Administration With Thesis', 'Master', 'Turkish', 2400, 2, true, 'الإدارة العامة مع أطروحة', 4000, NULL::numeric),
  ('Public Relations And Advertising With Thesis', 'Master', 'Turkish', 2400, 2, true, 'العلاقات العامة والإعلان مع أطروحة', 4000, NULL::numeric),
  ('Tourism And Hotel Management With Thesis', 'Master', 'Turkish', 2400, 2, true, 'إدارة السياحة والفنادق مع أطروحة', 4000, NULL::numeric),
  ('Architecture', 'PhD', 'Turkish', 6000, 4, true, 'هندسة معمارية', 9000, NULL::numeric),
  ('Business Administration', 'PhD', 'Turkish', 6000, 4, true, 'إدارة الأعمال', 9000, NULL::numeric),
  ('Civil Engineering', 'PhD', 'Turkish', 6000, 4, true, 'الهندسة المدنية', 9000, NULL::numeric),
  ('Clinical Pharmacy', 'PhD', 'Turkish', 6000, 4, true, 'الصيدلة السريرية', 9000, NULL::numeric),
  ('Communication Studies', 'PhD', 'Turkish', 6000, 4, true, 'دراسات الاتصال', 9000, NULL::numeric),
  ('Computer Engineering', 'PhD', 'Turkish', 6000, 4, true, 'هندسة كمبيوتر', 9000, NULL::numeric),
  ('Electrical and Electronic Engineering', 'PhD', 'Turkish', 6000, 4, true, 'هندسة كهرباء وإلكترون', 9000, NULL::numeric),
  ('English Language Teaching', 'PhD', 'Turkish', 6000, 4, true, 'تدريس اللغة الانجليزية', 9000, NULL::numeric),
  ('Environmental Sciences', 'PhD', 'Turkish', 6000, 4, true, 'العلوم البيئية', 9000, NULL::numeric),
  ('Health Management', 'PhD', 'Turkish', 6000, 4, true, 'الإدارة الصحية', 9000, NULL::numeric),
  ('Horticultural Production', 'PhD', 'Turkish', 6000, 4, true, 'الإنتاج البستاني', 9000, NULL::numeric),
  ('International Law', 'PhD', 'Turkish', 6000, 4, true, 'القانون الدولي', 9000, NULL::numeric),
  ('International Relations', 'PhD', 'Turkish', 6000, 4, true, 'علاقات دولية', 9000, NULL::numeric),
  ('Management Information Systems', 'PhD', 'Turkish', 6000, 4, true, 'نظم المعلومات الادارية', 9000, NULL::numeric),
  ('Nursing', 'PhD', 'Turkish', 6000, 4, true, 'تمريض', 9000, NULL::numeric),
  ('Nutrition And Dietetics', 'PhD', 'Turkish', 6000, 4, true, 'التغذية والحمية', 9000, NULL::numeric),
  ('Oral Maxillofacial Surgery', 'PhD', 'Turkish', 6000, 4, true, 'جراحة الفم والوجه والفكين', 9000, NULL::numeric),
  ('Orthodontics', 'PhD', 'Turkish', 6000, 4, true, 'تقويم الأسنان', 9000, NULL::numeric),
  ('Pedodontics', 'PhD', 'Turkish', 6000, 4, true, 'طب أسنان الأطفال', 9000, NULL::numeric),
  ('Pharmaceutical Sciences', 'PhD', 'Turkish', 6000, 4, true, 'العلوم الصيدلانية', 9000, NULL::numeric),
  ('Physiotherapy And Rehabilitation', 'PhD', 'Turkish', 6000, 4, true, 'العلاج الطبيعي وإعادة التأهيل', 9000, NULL::numeric),
  ('Prosthetic Dentistry', 'PhD', 'Turkish', 6000, 4, true, 'طب الأسنان الاصطناعي', 9000, NULL::numeric),
  ('Restorative Dentistry', 'PhD', 'Turkish', 6000, 4, true, 'طب الأسنان الترميمي', 9000, NULL::numeric)
) AS v(name, degree, language, cost, years, available, name_ar, before_discount, cash_price)
LEFT JOIN program p
  ON p.university_id = u.id
 AND lower(trim(p.name)) = lower(trim(v.name))
 AND COALESCE(p.degree, '') = COALESCE(v.degree, '')
 AND COALESCE(p.language, '') = COALESCE(v.language, '')
WHERE lower(trim(u.name)) = lower(trim('European University of Lefke'))
  AND p.id IS NULL;


INSERT INTO program (id, university_id, name, degree, language, cost, years, created_at, available, name_ar, before_discount, cash_price, updated_at)
SELECT gen_random_uuid(), u.id,
  v.name, v.degree, v.language, v.cost, v.years, now(), v.available, v.name_ar, v.before_discount, v.cash_price, now()
FROM university u
CROSS JOIN (
  VALUES
  ('Arabic Language Teaching', 'Bachelor', 'Turkish', 5000, 4, true, 'تدريس اللغة العربية', 5000, NULL::numeric),
  ('Architecture', 'Bachelor', 'Turkish', 5000, 4, true, 'هندسة معمارية', 5000, NULL::numeric),
  ('Aviation Management', 'Bachelor', 'English', 7000, 4, true, 'إدارة الطيران', 7000, NULL::numeric),
  ('Business Administration', 'Bachelor', 'English', 7000, 4, true, 'إدارة الأعمال', 7000, NULL::numeric),
  ('Civil Engineering', 'Bachelor', 'English', 5000, 4, true, 'الهندسة المدنية', 5000, NULL::numeric),
  ('Civil Engineering', 'Bachelor', 'Turkish', 5000, 4, true, 'الهندسة المدنية', 5000, NULL::numeric),
  ('Computer Engineering', 'Bachelor', 'English', 6000, 4, true, 'هندسة كمبيوتر', 6000, NULL::numeric),
  ('Computer Engineering', 'Bachelor', 'Turkish', 6000, 4, true, 'هندسة كمبيوتر', 6000, NULL::numeric),
  ('Conservation And Restoration Of Cultural Assets', 'Bachelor', 'English', 5000, 4, true, 'حفظ وترميم الأصول الثقافية', 5000, NULL::numeric),
  ('Conservation And Restoration Of Cultural Assets', 'Bachelor', 'Turkish', 5000, 4, true, 'حفظ وترميم الأصول الثقافية', 5000, NULL::numeric),
  ('Electrical And Electronic Engineering', 'Bachelor', 'Turkish', 6000, 4, true, 'هندسة كهرباء والكترون', 6000, NULL::numeric),
  ('English Translation And Interpretation', 'Bachelor', 'English', 7000, 4, true, 'الترجمة التحريرية ( تركي - إنجليزي )', 7000, NULL::numeric),
  ('English Translation And Interpretation', 'Bachelor', 'Turkish', 7000, 4, true, 'الترجمة التحريرية ( تركي - إنجليزي )', 7000, NULL::numeric),
  ('Graphic Design', 'Bachelor', 'Turkish', 7000, 4, true, 'تصميم جرافيك', 7000, NULL::numeric),
  ('Historical Sciences', 'Bachelor', 'Turkish', 5000, 4, true, 'العلوم التاريخية', 5000, NULL::numeric),
  ('History', 'Bachelor', 'Turkish', 5000, 4, true, 'التاريخ', 5000, NULL::numeric),
  ('Information System And Technologies', 'Bachelor', 'English', 7000, 4, true, 'نظم وتقنيات المعلومات', 7000, NULL::numeric),
  ('Interior Architecture', 'Bachelor', 'English', 6000, 4, true, 'عمارة داخلية', 6000, NULL::numeric),
  ('Interior Architecture', 'Bachelor', 'Turkish', 6000, 4, true, 'عمارة داخلية', 6000, NULL::numeric),
  ('Islamic Sciences', 'Bachelor', 'Turkish', 6000, 4, true, 'العلوم الإسلامية', 6000, NULL::numeric),
  ('Law', 'Bachelor', 'Turkish', 7000, 4, true, 'حقوق', 7000, NULL::numeric),
  ('Physiotherapy And Rehabilitation', 'Bachelor', 'Turkish', 6000, 4, true, 'العلاج الطبيعي وإعادة التأهيل', 6000, NULL::numeric),
  ('Political Science And International Relations', 'Bachelor', 'English', 7000, 4, true, 'العلوم السياسية والعلاقات الدولية', 7000, NULL::numeric),
  ('Preschool Education', 'Bachelor', 'Turkish', 6000, 4, true, 'التعليم ما قبل المدرسي', 6000, NULL::numeric),
  ('Psychology', 'Bachelor', 'English', 7000, 4, true, 'علم النفس', 7000, NULL::numeric),
  ('Psychology', 'Bachelor', 'Turkish', 7000, 4, true, 'علم النفس', 7000, NULL::numeric),
  ('Software Engineering', 'Bachelor', 'English', 7000, 4, true, 'هندسة البرمجيات', 7000, NULL::numeric),
  ('Special Education', 'Bachelor', 'Turkish', 6000, 4, true, 'التربية الخاصة', 6000, NULL::numeric),
  ('Traditional Turkish Arts', 'Bachelor', 'Turkish', 6000, 4, true, 'الفنون التركية التقليدية', 6000, NULL::numeric),
  ('Turkish Language And Literature', 'Bachelor', 'Turkish', 5000, 4, true, 'اللغة والأدب التركي', 5000, NULL::numeric),
  ('Turkish Language Teaching', 'Bachelor', 'Turkish', 5000, 4, true, 'تدريس اللغة التركية', 5000, NULL::numeric),
  ('Architectural Restoration', 'Diploma', 'Turkish', 3500, 2, true, 'الترميم المعماري', 4000, NULL::numeric),
  ('Child Development (Evening Class)', 'Diploma', 'Turkish', 3500, 2, true, 'تنمية الطفل (فصل مسائي)', 4000, NULL::numeric),
  ('Civil Aviation Cabin Services', 'Diploma', 'Turkish', 4000, 2, true, 'خدمات مقصورة الطيران المدني', 4500, NULL::numeric),
  ('Court And Office Management', 'Diploma', 'Turkish', 3500, 2, true, 'إدارة المحاكم والمكاتب', 4000, NULL::numeric),
  ('Information Security Technologies', 'Diploma', 'Turkish', 4000, 2, true, 'تقنيات أمن المعلومات', 4500, NULL::numeric),
  ('Packaging Design Program', 'Diploma', 'Turkish', 3500, 2, true, 'برنامج تصميم التعبئة والتغليف', 4000, NULL::numeric),
  ('Shadow Teaching For Disabled Individuals', 'Diploma', 'Turkish', 3500, 2, true, 'التعليم الظل للأفراد ذوي الإعاقة', 4000, NULL::numeric),
  ('Arabic Language And Education With Thesis', 'Master', 'Turkish', 3000, 2, true, 'اللغة العربية والتعليم مع أطروحة', 3000, NULL::numeric),
  ('Architectural Conservation Restoration With Thesis', 'Master', 'Turkish', 3000, 1, true, 'الحفاظ المعماري والترميم مع أطروحة', 3000, NULL::numeric),
  ('Architecture With Thesis', 'Master', 'English', 3500, 2, true, 'هندسة معمارية مع أطروحة', 3500, NULL::numeric),
  ('Architecture With Thesis', 'Master', 'Turkish', 3000, 2, true, 'هندسة معمارية مع أطروحة', 3000, NULL::numeric),
  ('Artificial Intelligence And Data Science', 'Master', 'Turkish', 3250, 1, true, 'الذكاء الاصطناعي وعلوم البيانات', 3250, NULL::numeric),
  ('Artificial Intelligence And Data Science With Thesis', 'Master', 'Turkish', 3500, 1, true, 'الذكاء الاصطناعي وعلوم البيانات مع أطروحة', 3500, NULL::numeric),
  ('Basic Islamic Sciences With Thesis', 'Master', 'Turkish', 3000, 2, true, 'العلوم الإسلامية الأساسية مع أطروحة', 3000, NULL::numeric),
  ('Business Administration', 'Master', 'English', 3250, 1, true, 'إدارة الأعمال', 3250, NULL::numeric),
  ('Business Administration With Thesis', 'Master', 'English', 3500, 2, true, 'إدارة الأعمال مع أطروحة', 3500, NULL::numeric),
  ('Civil Engineering With Thesis', 'Master', 'Turkish', 3000, 2, true, 'الهندسة المدنية مع أطروحة', 3000, NULL::numeric),
  ('Clinical Psychology', 'Master', 'Turkish', 3500, 2, true, 'علم النفس السريري', 3500, NULL::numeric),
  ('Computer Engineering With Thesis', 'Master', 'Turkish', 3000, 2, true, 'هندسة كمبيوتر مع أطروحة', 3000, NULL::numeric),
  ('Educational Administration', 'Master', 'Turkish', 3000, 1, true, 'الإدارة التربوية', 3000, NULL::numeric),
  ('Educational Administration With Thesis', 'Master', 'Turkish', 3000, 2, true, 'الإدارة التربوية مع أطروحة', 3000, NULL::numeric),
  ('Electrical And Electronic Engineering With The', 'Master', 'Turkish', 3500, 1, true, 'هندسة كهرباء والكترون مع أطروحة', 3500, NULL::numeric),
  ('Graphic Design With Thesis', 'Master', 'Turkish', 3000, 2, true, 'تصميم جرافيك مع أطروحة', 3000, NULL::numeric),
  ('History Of Science With Thesis', 'Master', 'Turkish', 3000, 2, true, 'تاريخ العلوم مع أطروحة', 3000, NULL::numeric),
  ('History With Thesis', 'Master', 'Turkish', 3000, 2, true, 'التاريخ مع أطروحة', 3000, NULL::numeric),
  ('Interior Architecture With Thesis', 'Master', 'Turkish', 3000, 2, true, 'عمارة داخلية مع أطروحة', 3000, NULL::numeric),
  ('Political Science And International Relations', 'Master', 'English', 3250, 1, true, 'العلوم السياسية والعلاقات الدولية', 3250, NULL::numeric),
  ('Political Science And International Relations W', 'Master', 'English', 3500, 1, true, 'العلوم السياسية والعلاقات الدولية مع أطروحة', 3500, NULL::numeric),
  ('Pre-School Education With Thesis', 'Master', 'Turkish', 3000, 2, true, 'التعليم ما قبل المدرسي مع أطروحة', 3000, NULL::numeric),
  ('Preservation And Management Of Cultural Heritage With Thesis', 'Master', 'Turkish', 3000, 1, true, 'الحفاظ على التراث الثقافي وإدارته مع أطروحة', 3000, NULL::numeric),
  ('Private Law With Thesis', 'Master', 'Turkish', 3000, 2, true, 'القانون الخاص مع أطروحة', 3000, NULL::numeric),
  ('Psychological Counselling And Guidance', 'Master', 'Turkish', 3000, 2, true, 'الإرشاد والتوجيه النفسي', 3000, NULL::numeric),
  ('Psychological Counselling And Guidance With Thesis', 'Master', 'Turkish', 3000, 1, true, 'الاستشارة والتوجيه النفسي مع أطروحة', 3000, NULL::numeric),
  ('Public Law With Thesis', 'Master', 'Turkish', 3000, 2, true, 'قانون عام مع أطروحة', 3000, NULL::numeric),
  ('Public Law With Thesis', 'Master', 'English', 3000, 2, true, 'قانون عام مع أطروحة', 3000, NULL::numeric),
  ('Teaching Turkish To Foreigners With Thesis', 'Master', 'Turkish', 3000, 2, true, 'تدريس اللغة التركية للأجانب مع أطروحة', 3000, NULL::numeric),
  ('Traditional Turkish Arts With Thesis', 'Master', 'Turkish', 3000, 2, true, 'الفنون التركية التقليدية مع أطروحة', 3000, NULL::numeric),
  ('Turkish Language And Literature With Thesis', 'Master', 'Turkish', 3000, 2, true, 'اللغة والأدب التركي مع أطروحة', 3000, NULL::numeric),
  ('Architecture', 'PhD', 'Turkish', 6500, 4, true, 'هندسة معمارية', 11000, NULL::numeric),
  ('Basic Islamic Sciences', 'PhD', 'Arabic', 8000, 4, true, 'العلوم الإسلامية الأساسية', 12000, NULL::numeric),
  ('Clinical Psychology', 'PhD', 'Turkish', 6500, 4, true, 'علم النفس السريري', 11000, NULL::numeric),
  ('Computer Engineering', 'PhD', 'Turkish', 6500, 4, true, 'هندسة كمبيوتر', 11000, NULL::numeric),
  ('Educational Administration', 'PhD', 'Turkish', 4500, 4, true, 'الإدارة التربوية', 9000, NULL::numeric),
  ('Graphic Design', 'PhD', 'Turkish', 4500, 4, true, 'تصميم جرافيك', 9000, NULL::numeric),
  ('History', 'PhD', 'Turkish', 4500, 4, true, 'التاريخ', 9000, NULL::numeric),
  ('History Of Islamic Science', 'PhD', 'Turkish', 4500, 4, true, 'تاريخ العلوم الإسلامية', 9000, NULL::numeric),
  ('Interior Architecture', 'PhD', 'Turkish', 4500, 4, true, 'عمارة داخلية', 9000, NULL::numeric),
  ('Preschool Education', 'PhD', 'Turkish', 4500, 4, true, 'التعليم ما قبل المدرسي', 9000, NULL::numeric),
  ('Psychological Counselling And Guidance', 'PhD', 'Turkish', 4500, 4, true, 'الإرشاد والتوجيه النفسي', 9000, NULL::numeric),
  ('Traditional Turkish Arts', 'PhD', 'Turkish', 4500, 4, true, 'الفنون التركية التقليدية', 9000, NULL::numeric),
  ('Turkish Language And Literature', 'PhD', 'Turkish', 4500, 4, true, 'اللغة والأدب التركي', 9000, NULL::numeric)
) AS v(name, degree, language, cost, years, available, name_ar, before_discount, cash_price)
LEFT JOIN program p
  ON p.university_id = u.id
 AND lower(trim(p.name)) = lower(trim(v.name))
 AND COALESCE(p.degree, '') = COALESCE(v.degree, '')
 AND COALESCE(p.language, '') = COALESCE(v.language, '')
WHERE lower(trim(u.name)) = lower(trim('Fatih Sultan Mehmet University'))
  AND p.id IS NULL;


INSERT INTO program (id, university_id, name, degree, language, cost, years, created_at, available, name_ar, before_discount, cash_price, updated_at)
SELECT gen_random_uuid(), u.id,
  v.name, v.degree, v.language, v.cost, v.years, now(), v.available, v.name_ar, v.before_discount, v.cash_price, now()
FROM university u
CROSS JOIN (
  VALUES
  ('Aerospace Engineering', 'Bachelor', 'English', 8250, 4, true, 'هندسة الطيران', 16500, NULL::numeric),
  ('Astronautical Engineering', 'Bachelor', 'English', 5000, 4, true, 'هندسة الملاحة الفضائية', 10000, NULL::numeric),
  ('Aviation Management', 'Bachelor', 'English', 5000, 4, true, 'إدارة الطيران', 10000, NULL::numeric),
  ('Computer Engineering', 'Bachelor', 'English', 5000, 4, true, 'هندسة كمبيوتر', 10000, NULL::numeric),
  ('Electrical And Electronic Engineering', 'Bachelor', 'English', 5000, 4, true, 'هندسة كهرباء والكترون', 10000, NULL::numeric),
  ('Flight Training', 'Bachelor', 'English', 12000, 4, true, 'التدريب على الطيران', 17500, NULL::numeric),
  ('Industrial Engineering', 'Bachelor', 'English', 5000, 4, true, 'هندسة صناعية', 10000, NULL::numeric),
  ('Logistics Management', 'Bachelor', 'English', 4000, 4, true, 'إدارة اللوجستية', 10000, NULL::numeric),
  ('Management', 'Bachelor', 'English', 4000, 4, true, 'الإدارة', 10000, NULL::numeric),
  ('Management Information Systems', 'Bachelor', 'English', 5000, 4, true, 'نظم المعلومات الادارية', 10000, NULL::numeric),
  ('Mechanical Engineering', 'Bachelor', 'English', 5000, 4, true, 'هندسة ميكانيك', 10000, NULL::numeric),
  ('Software Engineering', 'Bachelor', 'English', 5000, 4, true, 'هندسة البرمجيات', 10000, NULL::numeric),
  ('Air Logistics', 'Diploma', 'Turkish', 3600, 2, true, 'اللوجستيات الجوية', 8750, NULL::numeric),
  ('Aircraft Electronics', 'Diploma', 'Turkish', 3600, 2, true, 'إلكترونيات الطائرات', 8750, NULL::numeric),
  ('Civil Air Transportation Management', 'Diploma', 'Turkish', 3600, 2, true, 'إدارة النقل الجوي المدني', 8750, NULL::numeric),
  ('Civil Aviation And Cabin Services', 'Diploma', 'Turkish', 3600, 2, true, 'الطيران المدني وخدمات المقصورة', 8750, NULL::numeric),
  ('Aerospace Engineering', 'Master', 'English', 6750, 1, false, 'هندسة الطيران', 9000, NULL::numeric),
  ('Aerospace Engineering', 'Master', 'Turkish', 6750, 1, false, 'هندسة الطيران', 9000, NULL::numeric),
  ('Aerospace Engineering With Thesis', 'Master', 'English', 6750, 2, false, 'هندسة الطيران مع أطروحة', 9000, NULL::numeric),
  ('Aviation Management', 'Master', 'Turkish', 6750, 1, false, 'إدارة الطيران', 9000, NULL::numeric),
  ('Aviation Management With Thesis', 'Master', 'English', 6750, 2, false, 'إدارة الطيران مع أطروحة', 9000, NULL::numeric),
  ('Aviation Management With Thesis', 'Master', 'Turkish', 6750, 2, false, 'إدارة الطيران مع أطروحة', 9000, NULL::numeric),
  ('Business Management With Thesis', 'Master', 'English', 6750, 2, false, 'إدارة الأعمال مع أطروحة', 9000, NULL::numeric),
  ('Electrical And Computer Engineering With Thesis', 'Master', 'English', 6750, 1, false, 'الهندسة الكهربائية والحاسوبية مع أطروحة', 9000, NULL::numeric),
  ('Flight Training', 'Master', 'English', 6750, 1, false, 'التدريب على الطيران', 9000, NULL::numeric),
  ('Mechanical and Aeronautical Engineering With Thesis', 'Master', 'English', 6750, 1, false, 'هندسة الميكانيكا والطيران مع أطروحة', 9000, NULL::numeric),
  ('Unmanned and Autonomous Systems Engineering With Thesis', 'Master', 'Turkish', 6750, 1, false, 'هندسة الأنظمة غير المأهولة والمستقلة مع أطروحة', 9000, NULL::numeric)
) AS v(name, degree, language, cost, years, available, name_ar, before_discount, cash_price)
LEFT JOIN program p
  ON p.university_id = u.id
 AND lower(trim(p.name)) = lower(trim(v.name))
 AND COALESCE(p.degree, '') = COALESCE(v.degree, '')
 AND COALESCE(p.language, '') = COALESCE(v.language, '')
WHERE lower(trim(u.name)) = lower(trim('Türk Hava Kurumu University'))
  AND p.id IS NULL;
