-- Agent portal university list (logos via Google favicon service from institution domain)
INSERT INTO university (id, name, country, website, currency, programs_count, campuses_count, logo_url, created_at)
SELECT gen_random_uuid(), v.name, NULLIF(trim(v.country), ''), v.website, v.currency, v.programs_count, v.campuses_count,
       'https://www.google.com/s2/favicons?domain=' || v.domain || '&sz=128',
       now()
FROM (VALUES
  ('Altınbaş University', 'Turkey', 'https://altinbas.edu.tr/', 'USD', 102, 3, 'altinbas.edu.tr'),
  ('Aydın University', 'Turkey', 'https://www.aydin.edu.tr/', 'USD', 429, 1, 'aydin.edu.tr'),
  ('Arel University', 'Turkey', 'https://international.arel.edu.tr/', 'USD', 124, 3, 'arel.edu.tr'),
  ('Atlas University', 'Turkey', 'https://www.atlas.edu.tr/', 'USD', 104, 1, 'atlas.edu.tr'),
  ('Lokman Hekim University', 'Turkey', 'https://www.lokmanhekim.edu.tr/', 'USD', 42, 1, 'lokmanhekim.edu.tr'),
  ('Hasan Kalyoncu University', 'Turkey', 'https://www.hku.edu.tr/eng/', 'USD', 52, 1, 'hku.edu.tr'),
  ('Kadir Has University', 'Turkey', 'https://www.khas.edu.tr/', 'USD', 26, 1, 'khas.edu.tr'),
  ('Fatih Sultan Mehmet University', 'Turkey', 'https://www.fsm.edu.tr/', 'USD', 90, 1, 'fsm.edu.tr'),
  ('Medipol University', 'Turkey', 'https://www.medipol.edu.tr/', 'USD', 142, 4, 'medipol.edu.tr'),
  ('CBAU University', 'Cyprus', 'https://bau.edu.tr/', 'EUR', 71, 1, 'bau.edu.tr'),
  ('Okan University', 'Turkey', 'https://www.okan.edu.tr/', 'USD', 327, 1, 'okan.edu.tr'),
  ('Haliç University', 'Turkey', 'https://halic.edu.tr/', 'USD', 153, 1, 'halic.edu.tr'),
  ('İstanbul Kültür University', 'Turkey', 'https://www.iku.edu.tr/', 'USD', 193, 4, 'iku.edu.tr'),
  ('Fenerbahçe University', 'Turkey', 'https://www.fbu.edu.tr/', 'USD', 71, 1, 'fbu.edu.tr'),
  ('Nişantaşı University', 'Turkey', 'https://www.nisantasi.edu.tr/', 'USD', 235, 1, 'nisantasi.edu.tr'),
  ('Kyrenia University', 'Cyprus', 'https://kyrenia.edu.tr/', 'EUR', 91, 0, 'kyrenia.edu.tr'),
  ('Üsküdar University', 'Turkey', 'https://uskudar.edu.tr/', 'USD', 196, 5, 'uskudar.edu.tr'),
  ('Bezmialem Vakıf University', 'Turkey', 'https://bezmialem.com.tr/', 'USD', 9, 1, 'bezmialem.com.tr'),
  ('Cyprus Science University', 'Cyprus', 'https://international.csu.edu.tr/', 'USD', 75, 1, 'csu.edu.tr'),
  ('Antalya Bilim University', 'Turkey', 'https://www.antalya.edu.tr/en', 'USD', 56, 1, 'antalya.edu.tr'),
  ('European University of Lefke', 'Cyprus', 'https://www.eul.edu.tr/tr/', 'EUR', 118, 1, 'eul.edu.tr'),
  ('Türk Hava Kurumu University', 'Turkey', 'https://www.thk.edu.tr/', 'USD', 27, 1, 'thk.edu.tr'),
  ('Ankara Science University', 'Turkey', 'https://ankarabilim.edu.tr/', 'USD', 33, 0, 'ankarabilim.edu.tr'),
  ('Ibn Haldun University', 'Turkey', 'https://www.ihu.edu.tr/tr', 'USD', 40, 3, 'ihu.edu.tr'),
  ('KSTU University', 'Cyprus', 'https://kstu.edu.tr/', 'USD', 80, 1, 'kstu.edu.tr'),
  ('Bahçeşehir University', 'Turkey', 'https://bau.edu.tr/', 'USD', 282, 9, 'bau.edu.tr'),
  ('Işık University', 'Turkey', 'https://www.isikun.edu.tr/', 'USD', 66, 2, 'isikun.edu.tr'),
  ('Kent University', 'Turkey', 'https://www.kent.edu.tr/', 'USD', 103, 2, 'kent.edu.tr'),
  ('İstinye University', 'Turkey', 'https://www.istinye.edu.tr/', 'USD', 174, 2, 'istinye.edu.tr'),
  ('Final International University', 'Cyprus', 'https://www.final.edu.tr/', 'USD', 70, 1, 'final.edu.tr'),
  ('Biruni University', 'Turkey', 'https://www.biruni.edu.tr/en/', 'USD', 105, 3, 'biruni.edu.tr'),
  ('CIU University', 'Cyprus', 'https://www.ciu.edu.tr/en', 'EUR', 148, 1, 'ciu.edu.tr'),
  ('Beykent University', 'Turkey', 'https://www.beykent.edu.tr/', 'USD', 188, 4, 'beykent.edu.tr'),
  ('Beykoz University', 'Turkey', 'https://www.beykoz.edu.tr/', 'USD', 67, 5, 'beykoz.edu.tr'),
  ('Medipol Ankara University', 'Turkey', 'https://ankaramedipol.edu.tr/', 'USD', 48, 2, 'ankaramedipol.edu.tr'),
  ('İstanbul Bilgi University', 'Turkey', 'https://www.bilgi.edu.tr/en/', 'USD', 140, 3, 'bilgi.edu.tr'),
  ('Girne American University', 'Cyprus', 'https://www.gau.edu.tr/', 'EUR', 126, 1, 'gau.edu.tr'),
  ('Near East University', 'Cyprus', 'https://neu.edu.tr/', 'EUR', 540, 1, 'neu.edu.tr'),
  ('Özyeğin University', 'Turkey', 'https://www.ozyegin.edu.tr/tr', 'USD', 27, 1, 'ozyegin.edu.tr'),
  ('Eastern Mediterranean University', 'Cyprus', 'https://www.emu.edu.tr/en', 'USD', 153, 1, 'emu.edu.tr'),
  ('İstanbul Sabahattin Zaim University', 'Turkey', 'https://www.izu.edu.tr/', 'USD', 136, 2, 'izu.edu.tr'),
  ('Topkapı University', 'Turkey', 'https://www.topkapi.edu.tr/', 'USD', 171, 7, 'topkapi.edu.tr'),
  ('İstanbul Gelişim University', 'Turkey', 'https://www.gelisim.edu.tr/', 'USD', 267, 9, 'gelisim.edu.tr'),
  ('Atılım University', 'Turkey', 'https://www.atilim.edu.tr/en', 'USD', 130, 2, 'atilim.edu.tr')
) AS v(name, country, website, currency, programs_count, campuses_count, domain)
WHERE NOT EXISTS (SELECT 1 FROM university u WHERE lower(trim(u.name)) = lower(trim(v.name)));
